directories:
  output: dist
  buildResources: build
appId: com.aftc.di-fm-desktop-app
productName: DI.FM
copyright: AFTC LTD
win:
  certificateFile: private/darcey.lloyd@gmail.com.pfx
  certificatePassword: <stripped sensitive data>
  verifyUpdateCodeSignature: false
linux:
  category: utility
mac:
  category: public.app-category.utilities
  target: dmg
electronVersion: 12.0.1
